### ISSUE TITLE
RDF bith:selection includes SVG bounding box IDs

### ISSUE THREAD

**Issue by DILewis** [DomesticBeethoven/bith-annotator#1] opened 2022-05-22 12:32 UTC
Selections created by the annotator and saved to solid include some 'real' fragment IDs for MEI elements and some strange, non-existent ones (e.g. https://raw.githubusercontent.com/DomesticBeethoven/data/main/mei/op.%2092/StimKlvAugener%20-%20D-BNba%20C92_48/D-BNbaC92_48.mei#bbox-mff6915a8-0cb3-4190-91c0-58cac8f099ec) 

These look like artefacts of the selection process. I can't tell from the examples I have whether contained elements are omitted.

The example selection I'm using is at [https://domesticb.solidcommunity.net/public/bith/selections/08c64f66-6c6b-4067-ac47-2d69b24de71b.ttl](https://domesticb.solidcommunity.net/public/bith/selections/08c64f66-6c6b-4067-ac47-2d69b24de71b.ttl)

**Comment by kepper** [comment] 2022-05-22 15:23
I have looked into this a bit, and a first solution is available. However, it raises some questions on expected behaviour. But first things first: 
By changing https://github.com/DomesticBeethoven/bith-annotator/blob/a9d60a7052e6d8366cd3aed9cc79f52b2d4d4eb2/src/components/Workbench/Verovio.vue#L77 to `selectables.push('.' + elem + ':not(.bounding-box)')`, we can avoid those `bbox-`-selections. However, rendition of the selected staff is then as if all the notes on that staff would have been selected individually. We could now either: 

- rebuild the old behaviour, i.e. still use the bbox for highlighting the full staff, or
- improve interaction with single symbol selection.

The latter will take definitely more work, but may be more sustainable. It basically means that when a full staff is selected, and then a single event on that staff is deselected, we would have to revise the whole selection, switching to a positive list of all the things that are still selected. That can turn out to be quite annoying, because what should happen when things are added back in? Shall we then move back to the staff being selected instead of individual events? 

Before I push my solution, I would like to step back and think about this briefly. What's your take, @DILewis?

**Comment by DILewis** [comment] 2022-05-22 15:32
Yes, when I encoded this sort of thing manually, I always looked for the hierarchical layer that caught the most elements (so measure or staff or whatever), but I can see how this could be exciting in an interactive setting. Also, my reasoning at the time was partly about saving myself typing and correction. 

Semantically, the only problem I can see with a positive list is if the list excludes symbols we would like included (e.g. if it only has notes, and we want hairpins included).

My instinct is that fine-tuning a selection by adding and removing a lot will be a rarer use case, so may not be _too_ bad..?

**Comment by kepper** [comment] 2022-06-28 07:22
fixed with c355b3088464282af481f045be87040bfbfd8b26. The behavior is now as follows: clicking on an event (or controlevent) will select just that. Clicking on the bounding box of a staff (as rendered transparently by Verovio) will select the staff, and shift-clicking on anything will select the whole measure (which isn't accessible easily otherwise). Repeated clicks will toggle following the same logic, i.e. there is no automatic translation of selections when everything inside a staff is selected, and it's not possible to deselect one note out of a measure. #2 can still be optimized, but the selection itself is stable for the time being, I think.

**Closed as completed by kepper** 2022-06-28 07:22 UTC
Labels: bug
